## 当前项目部署的端口
server:
    port: 9993
## 将当前服务注册到服务中心
eureka:
    client:
        service-url:
            defaultZone: http://localhost:9991/eureka/
## 当前项目的名称
spring:
    application:
        name: service-ribbon